import {useState,useEffect,useRef} from 'react';
import {BrowserProvider,getAddress} from 'ethers';
import {CHAIN,userError} from './chain';
export function useWallet(){
 const [available,setAvailable]=useState([]),[session,setSession]=useState(null),[connecting,setConnecting]=useState(false),[error,setError]=useState('');
 const active=useRef(null),generation=useRef(0);
 useEffect(()=>{const announced=e=>{const d=e.detail;if(!d?.provider?.request)return;setAvailable(prev=>prev.some(w=>w.provider===d.provider)?prev:[...prev,{name:d.info?.name||'Browser wallet',provider:d.provider,uuid:d.info?.uuid}])};window.addEventListener('eip6963:announceProvider',announced);window.dispatchEvent(new Event('eip6963:requestProvider'));if(window.ethereum){const providers=window.ethereum.providers||[window.ethereum];setAvailable(prev=>[...prev,...providers.filter(p=>!prev.some(w=>w.provider===p)).map((p,i)=>({name:p.isMetaMask?'MetaMask':p.isCoinbaseWallet?'Coinbase Wallet':p.isBitKeep?'Bitget Wallet':'Browser wallet',provider:p,uuid:'injected-'+i}))])}return()=>window.removeEventListener('eip6963:announceProvider',announced)},[]);
 async function switchNetwork(raw){const current=Number(await raw.request({method:'eth_chainId'}));if(current===CHAIN.id)return;try{await raw.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN.hex}]})}catch(e){if((e.code??e.data?.originalError?.code)!==4902)throw e;await raw.request({method:'wallet_addEthereumChain',params:[{chainId:CHAIN.hex,chainName:CHAIN.name,nativeCurrency:{name:'BOT',symbol:'BOT',decimals:18},rpcUrls:[CHAIN.rpc],blockExplorerUrls:[CHAIN.explorer]}]});await raw.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN.hex}]})}if(Number(await raw.request({method:'eth_chainId'}))!==CHAIN.id)throw Error('network')}
 async function connect(wallet){if(connecting)return;setConnecting(true);setError('');const version=++generation.current;try{const raw=wallet.provider;const accounts=await raw.request({method:'eth_requestAccounts'});if(!accounts?.length)throw Error('No account');await switchNetwork(raw);const provider=new BrowserProvider(raw,'any');const signer=await provider.getSigner(getAddress(accounts[0]));if(version!==generation.current)return;active.current=raw;setSession({address:await signer.getAddress(),signer,provider,raw,name:wallet.name,chainId:CHAIN.id})}catch(e){setError(userError(e,'connect your wallet'))}finally{setConnecting(false)}}
 async function disconnect(){++generation.current;const raw=active.current;active.current=null;setSession(null);setError('');try{await raw?.request({method:'wallet_revokePermissions',params:[{eth_accounts:{}}]})}catch{}window.location.hash='/'}
 async function reconnectNetwork(){if(!session)return;setConnecting(true);try{await switchNetwork(session.raw);const provider=new BrowserProvider(session.raw,'any');const signer=await provider.getSigner(session.address);setSession(s=>s?{...s,provider,signer,chainId:CHAIN.id}:null);setError('')}catch(e){setError(userError(e,'switch to BOT Chain Testnet'))}finally{setConnecting(false)}}
 useEffect(()=>{if(!session)return;const raw=session.raw;const accountsChanged=()=>{++generation.current;active.current=null;setSession(null);setError('Your wallet account changed. Connect the account you want to use.');window.location.hash='/'};const chainChanged=id=>{setSession(s=>s?{...s,chainId:Number(id)}:null)};const removed=()=>{active.current=null;setSession(null);window.location.hash='/'};raw.on?.('accountsChanged',accountsChanged);raw.on?.('chainChanged',chainChanged);raw.on?.('disconnect',removed);return()=>{raw.removeListener?.('accountsChanged',accountsChanged);raw.removeListener?.('chainChanged',chainChanged);raw.removeListener?.('disconnect',removed)}},[session?.raw]);
 return {available,session,connecting,error,setError,connect,disconnect,reconnectNetwork};
}
