import React,{useState,useEffect,useRef} from 'react';
import {ScanLine,Camera,ImagePlus,ShieldCheck,ArrowRight,Check,Square} from 'lucide-react';
import {Empty,Notice,Loading,dateTime} from '../components/Shared';
import {CHAIN,ADDRESS,contract,reader,eventFromChain,sameAddress,shortAddress,userError} from '../lib/chain';
class EntryError extends Error {}
function parseProof(text){let p;try{p=JSON.parse(text.trim())}catch{throw new EntryError('Paste the full signed QR contents, or scan the attendee’s QR code. A ticket number alone cannot prove ownership.')}if(p.app!=='Ticketa'||Number(p.chainId)!==CHAIN.id||!sameAddress(p.contract,ADDRESS))throw new EntryError('This QR code is not for this Ticketa deployment on BOT Chain Testnet.');if(!/^\d+$/.test(String(p.ticketId))||!/^\d+$/.test(String(p.nonce))||!Number.isSafeInteger(p.deadline)||typeof p.signature!=='string'||!/^0x[0-9a-f]+$/i.test(p.signature))throw new EntryError('This QR code is incomplete. Ask the attendee to generate a new code.');return p}
export default function CheckIn({data,address,busy,onCheckIn}){
 const allowed=data.events.filter(e=>data.staffIds.includes(e.id));const [selected,setSelected]=useState(''),[text,setText]=useState(''),[preview,setPreview]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[scanning,setScanning]=useState(false);
 const video=useRef(null),controls=useRef(null),input=useRef(null),mounted=useRef(true),generation=useRef(0);
 useEffect(()=>{if(!selected&&allowed.length)setSelected(String(allowed[0].id))},[allowed.length]);
 useEffect(()=>()=>{mounted.current=false;generation.current++;controls.current?.stop()},[]);
 useEffect(()=>{if(!scanning)return;let cancelled=false;async function start(){try{const {BrowserQRCodeReader}=await import('@zxing/browser');const reader=new BrowserQRCodeReader();const scanner=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},video.current,(result,err,control)=>{if(result&&!cancelled){control.stop();setScanning(false);const content=result.getText();setText(content);inspect(content)}});if(cancelled)scanner.stop();else controls.current=scanner}catch(err){if(!cancelled){setScanning(false);setError(err.name==='NotAllowedError'?'Camera access was denied. Allow camera access in your browser, or upload a QR image.':'The camera could not be opened. Check that it is available, or upload a QR image.')}}}start();return()=>{cancelled=true;controls.current?.stop();controls.current=null}},[scanning]);
 async function inspect(content=text){setError('');setPreview(null);setLoading(true);const version=++generation.current;try{const proof=parseProof(content);const info=await contract.ticketInfo(proof.ticketId);if(info.eventId===0n)throw new EntryError('This ticket does not exist. Ask the attendee to open their ticket in Ticketa.');if(info.used)throw new EntryError('This ticket has already been checked in.');if(String(info.eventId)!==selected)throw new EntryError('This ticket belongs to a different event. Select the correct event before checking it in.');const [view,owner,block,valid]=await Promise.all([contract.getFunction('getEvent')(info.eventId),contract.ownerOf(proof.ticketId),reader.getBlock('latest'),contract.proofIsValid(proof.ticketId,proof.nonce,proof.deadline,proof.signature)]);if(proof.deadline<block.timestamp)throw new EntryError('This QR code has expired. Ask the attendee to generate a new code.');if(!valid)throw new EntryError('The signature is invalid or the ticket changed owners. Ask the current owner to generate a new code.');const e=eventFromChain(view);const staff=sameAddress(e.organizer,address)||await contract.checkInStaff(e.id,address);if(!staff)throw new EntryError('Your wallet is not authorized for this event. Ask the organizer to add you as staff.');if(block.timestamp<e.startsAt||block.timestamp>e.endsAt)throw new EntryError('Check-in is available from '+dateTime(e.startsAt)+' to '+dateTime(e.endsAt)+'.');if(mounted.current&&version===generation.current)setPreview({proof,event:e,owner,tier:e.tiers[Number(info.tierId)]})}catch(err){if(mounted.current&&version===generation.current)setError(err instanceof EntryError?err.message:userError(err,'verify this ticket'))}finally{if(mounted.current&&version===generation.current)setLoading(false)}}
 async function upload(ev){const file=ev.target.files?.[0];ev.target.value='';if(!file)return;setError('');setLoading(true);const url=URL.createObjectURL(file);try{const {BrowserQRCodeReader}=await import('@zxing/browser');const result=await new BrowserQRCodeReader().decodeFromImageUrl(url);const content=result.getText();setText(content);await inspect(content)}catch{setError('No readable QR code was found in this image. Upload a clear image of the full code.')}finally{URL.revokeObjectURL(url);setLoading(false)}}
 if(!allowed.length)return <section className="panel"><Empty icon={ScanLine} title="No check-in access">Create an event or ask an organizer to authorize your wallet as check-in staff. Your authorized events will appear here.</Empty></section>;
 return <section className="panel checkin-panel"><div className="checkin-heading"><div className="stat-icon blue"><ScanLine size={24}/></div><div><h2>Verify entry</h2><p className="muted">Scan the attendee’s signed QR code. Check-in must be confirmed on-chain.</p></div></div><label>Event<select value={selected} onChange={e=>{generation.current++;setSelected(e.target.value);setPreview(null);setError('');setScanning(false)}}>{allowed.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{error&&<Notice>{error}</Notice>}<div className="scan-actions"><button className="outline-button" disabled={busy||loading} onClick={()=>{setError('');setScanning(!scanning)}}>{scanning?<><Square size={16}/>Stop camera</>:<><Camera size={17}/>Scan with camera</>}</button><button className="outline-button" disabled={busy||loading} onClick={()=>input.current.click()}><ImagePlus size={17}/>Upload QR image</button><input ref={input} type="file" accept="image/*" hidden onChange={upload}/></div>{scanning&&<div className="scanner"><video ref={video} muted playsInline/><div className="scanner-guide"/><p>Place the complete QR code inside the frame.</p></div>}<form onSubmit={e=>{e.preventDefault();inspect()}}><label>Signed QR contents<textarea value={text} onChange={e=>{setText(e.target.value);setPreview(null)}} rows={4} required placeholder="Paste the full QR contents here"/></label><button className="primary-button" disabled={loading||busy}>Verify ticket<ShieldCheck size={17}/></button></form>{loading&&<Loading text="Verifying ticket ownership…"/>}{preview&&<div className="checkin-preview"><span className="status"><ShieldCheck size={13}/>Owner signature verified</span><h3>{preview.event.name}</h3><p>Ticket #{preview.proof.ticketId} · {preview.tier.name}</p><p>Owner: {shortAddress(preview.owner)}</p><button className="primary-button full" disabled={busy} onClick={()=>onCheckIn(preview.proof,()=>{setPreview(null);setText('')})}>{busy?'Waiting for confirmation…':'Confirm check-in'}<Check size={17}/></button></div>}<p className="field-help">Only the organizer and authorized staff can check in tickets. Each ticket can be used once.</p></section>
}
