import React,{useState} from 'react';
import {Search,MapPin,Clock,ArrowUpRight,ArrowRight,CalendarDays,Ticket,ShieldCheck,Users,ArrowLeft} from 'lucide-react';
import {Empty,dateTime,eventState} from '../components/Shared';
import {amount,imageUrl,shortAddress,explorerAddress,sameAddress} from '../lib/chain';
export function Stat({icon:Icon,label,value,hint,color='blue'}){return <div className="stat"><div className={'stat-icon '+color}><Icon size={21}/></div><div><span>{label}</span><h3>{value}</h3><p>{hint}</p></div></div>}
export function EventCard({event:e,now,onOpen}){const date=new Date(e.startsAt*1000);const available=e.tiers.filter(t=>t.minted<t.capacity);const minimum=(available.length?available:e.tiers).reduce((a,t)=>t.price<a?t.price:a,e.tiers[0].price);return <button className="event-card" onClick={()=>onOpen(e.id)}><div className="event-image"><img src={imageUrl(e.imageUrl)} alt="" onError={ev=>{ev.currentTarget.onerror=null;ev.currentTarget.src='/event-cover.svg'}}/><span className="event-badge blue">{eventState(e,now)}</span><span className="date-badge"><strong>{date.getDate().toString().padStart(2,'0')}</strong><span>{date.toLocaleString(undefined,{month:'short'}).toUpperCase()}</span></span><span className="image-arrow"><ArrowUpRight size={19}/></span></div><div className="event-body"><span className="category">{e.category||'Event'}</span><h3>{e.name}</h3><p><MapPin size={13}/>{e.venue}</p><div className="event-card-bottom"><span><Clock size={13}/>{date.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</span><strong>{available.length?amount(minimum):'Sold out'}{available.length>0&&<><small> BOT</small><span> from</span></>}</strong></div></div></button>}
export function Events({data,onOpen,onCreate,overview=false,onExplore}){
 const [category,setCategory]=useState('All events'),[search,setSearch]=useState(''),[status,setStatus]=useState('Upcoming');
 const now=data.timestamp+(Date.now()-data.updatedAt)/1000;
 const categories=['All events',...new Set(data.events.map(e=>e.category).filter(Boolean))];
 const filtered=data.events.filter(e=>(category==='All events'||e.category===category)&&(!search||(e.name+' '+e.venue).toLowerCase().includes(search.toLowerCase()))&&(status==='All dates'||(status==='Upcoming'?e.endsAt>now:e.endsAt<=now))).sort((a,b)=>a.startsAt-b.startsAt);
 const displayed=overview?filtered.slice(0,3):filtered;
 return <>{overview&&<><section className="hero dashboard-hero"><div className="hero-content"><span className="hero-badge"><span/>BOT CHAIN TESTNET</span><h2>Your tickets.<br/><span>In one place.</span></h2><p>Find events, view your tickets, and manage entry.<br/>All ticket activity is recorded on BOT Chain.</p><button className="primary-button" onClick={onExplore}>Explore events<ArrowRight size={17}/></button></div><div className="dashboard-hero-icon"><Ticket size={112} strokeWidth={1}/><span>Your ticket. Your wallet. Your proof.</span></div></section><section className="stats"><Stat icon={Ticket} label="Tickets owned" value={data.tickets.length} hint="In your connected wallet"/><Stat icon={ShieldCheck} label="Unused tickets" value={data.tickets.filter(t=>!t.used).length} hint="Not checked in" color="green"/><Stat icon={CalendarDays} label="Upcoming events" value={data.events.filter(e=>e.endsAt>now).length} hint="Published on Ticketa" color="orange"/><Stat icon={Users} label="Checked-in tickets" value={data.tickets.filter(t=>t.used).length} hint="In your connected wallet" color="purple"/></section></>}<section className="event-section"><div className="section-title"><div><h2>{overview?'Upcoming events':'Events'}<span className="small-count">{filtered.length}</span></h2><p>Times shown in your local timezone.</p></div>{overview&&<button className="text-button" onClick={onExplore}>View all events<ArrowRight size={16}/></button>}</div><div className="event-controls"><div className="tabs">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="search"><Search size={16}/><input aria-label="Search events" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events"/></div><select className="date-filter" aria-label="Filter by date" value={status} onChange={e=>setStatus(e.target.value)}><option>Upcoming</option><option>Past</option><option>All dates</option></select></div>{displayed.length?<div className="event-grid">{displayed.map(e=><EventCard key={e.id} event={e} now={now} onOpen={onOpen}/>)}</div>:<Empty icon={CalendarDays} title={data.events.length?'No matching events':'No events published yet'} action={data.events.length?()=>{setSearch('');setCategory('All events');setStatus('All dates')}:onCreate} label={data.events.length?'Clear filters':'Create event'}>{data.events.length?'Try another search, category, or date.':'Events will appear here after an organizer publishes them on BOT Chain.'}</Empty>}</section></>
}
export function EventDetails({event:e,data,address,busy,onBuy,onManage,onBack}){
 const [tierId,setTierId]=useState(0);const tier=e.tiers[tierId];const now=data.timestamp+(Date.now()-data.updatedAt)/1000;const salesOpen=now<e.startsAt;const remaining=tier.capacity-tier.minted;
 return <><button className="text-button back-link" onClick={onBack}><ArrowLeft size={16}/>Back to events</button><div className="event-detail-grid"><section className="panel event-detail"><img className="event-detail-image" src={imageUrl(e.imageUrl)} alt="" onError={ev=>{ev.currentTarget.onerror=null;ev.currentTarget.src='/event-cover.svg'}}/><div className="event-detail-content"><span className="category">{e.category}</span><h2>{e.name}</h2><span className="status">{eventState(e,now)}</span><div className="event-detail-meta"><p><CalendarDays size={18}/><span>{dateTime(e.startsAt)}<small>Ends {dateTime(e.endsAt)}</small></span></p><p><MapPin size={18}/>{e.venue}</p><p><Users size={18}/><a href={explorerAddress(e.organizer)} target="_blank" rel="noreferrer">Organizer {shortAddress(e.organizer)}<ArrowUpRight size={13}/></a></p></div><h3>About this event</h3><p className="event-description">{e.description||'The organizer has not added a description.'}</p></div></section><section className="panel purchase-panel"><h2>Tickets</h2><p className="muted">Choose a ticket tier. Prices are in testnet BOT.</p><div className="tier-options">{e.tiers.map(t=><button key={t.id} className={tierId===t.id?'selected':''} onClick={()=>setTierId(t.id)} disabled={busy}><span><strong>{t.name}</strong><small>{t.capacity-t.minted} remaining of {t.capacity}</small></span><strong>{amount(t.price)} BOT</strong></button>)}</div><div className="purchase-total"><span>1 × {tier.name}</span><strong>{amount(tier.price)} <small>BOT</small></strong></div><button className="primary-button full" disabled={busy||!salesOpen||remaining<=0} onClick={()=>onBuy(e,tier)}>{busy?'Waiting for confirmation…':!salesOpen?'Sales closed':remaining<=0?'Sold out':tier.price===0n?'Claim ticket':'Buy ticket'}<ArrowRight size={17}/></button><p className="fine-print">A network fee applies. Your ticket is minted to your connected wallet after the transaction confirms.</p>{sameAddress(e.organizer,address)&&<button className="outline-button full manage-event-link" onClick={()=>onManage(e.id)}>Manage event<ArrowUpRight size={16}/></button>}</section></div></>
}
