import React,{useState,useEffect} from 'react';
import {Ticket,ScanLine,ArrowLeftRight,ArrowUpRight,Download,ShieldCheck,LoaderCircle} from 'lucide-react';
import QRCode from 'qrcode';
import {Modal,Empty,Notice,dateTime} from '../components/Shared';
import {CHAIN,ADDRESS,contract,reader,imageUrl,shortAddress,explorerAddress,proofDomain,proofTypes,sameAddress,userError} from '../lib/chain';
export function Tickets({data,onExplore,onTicket,onTransfer,busy}){const [filter,setFilter]=useState('All tickets');const filtered=data.tickets.filter(t=>filter==='All tickets'||(filter==='Unused'?!t.used:t.used));return <section className="panel"><div className="section-title"><h2>My tickets <span className="small-count">{data.tickets.length}</span></h2><div className="tabs">{['All tickets','Unused','Checked in'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>{filtered.length?<div className="event-grid ticket-grid">{filtered.map(t=>{const e=data.events.find(e=>e.id===t.eventId);if(!e)return null;return <article className="owned-ticket" key={t.id}><img src={imageUrl(e.imageUrl)} alt="" onError={ev=>{ev.currentTarget.onerror=null;ev.currentTarget.src='/event-cover.svg'}}/><div><span className={'status '+(t.used?'used':'')}>{t.used?'Checked in':'Unused'}</span><h3>{e.name}</h3><p>{dateTime(e.startsAt)}</p><p>{e.venue}</p><div className="ticket-tier-line"><span>{e.tiers[t.tierId]?.name}</span><strong>#{t.id}</strong></div><div className="ticket-actions"><button className="primary-button" onClick={()=>onTicket(t)}><ScanLine size={16}/>View ticket</button><button className="icon-button" aria-label={'Transfer ticket '+t.id} disabled={t.used||busy} onClick={()=>onTransfer(t)}><ArrowLeftRight size={18}/></button></div></div></article>})}</div>:<Empty title={filter==='All tickets'?'No tickets in this wallet':'No '+filter.toLowerCase()+' tickets'} action={onExplore} label="Explore events">Purchased and received tickets will appear here once their transactions confirm.</Empty>}</section>}
export function TicketDialog({ticket:t,event:e,session,onClose,onTransfer}){
 const [proof,setProof]=useState(null),[qr,setQr]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{setProof(null);setQr('')},[t.nonce,t.used]);
 async function generate(){setError('');setBusy(true);try{const accounts=await session.raw.request({method:'eth_accounts'});if(!sameAddress(accounts[0],session.address)||Number(await session.raw.request({method:'eth_chainId'}))!==CHAIN.id){setError('Reconnect the ticket owner’s wallet on BOT Chain Testnet.');return}const [owner,info,block]=await Promise.all([contract.ownerOf(t.id),contract.ticketInfo(t.id),reader.getBlock('latest')]);if(!sameAddress(owner,session.address)){setError('This wallet no longer owns the ticket. Refresh your collection.');return}if(info.used){setError('This ticket has already been checked in.');return}const deadline=block.timestamp+600;const signature=await session.signer.signTypedData(proofDomain,proofTypes,{ticketId:t.id,nonce:info.nonce,deadline});const payload={app:'Ticketa',chainId:CHAIN.id,contract:ADDRESS,ticketId:String(t.id),nonce:info.nonce.toString(),deadline,signature};const valid=await contract.proofIsValid(t.id,info.nonce,deadline,signature);if(!valid){setError('The code expired while signing, or ticket ownership changed. Generate a new code.');return}setQr(await QRCode.toDataURL(JSON.stringify(payload),{width:340,margin:2,errorCorrectionLevel:'M',color:{dark:'#0C1222',light:'#FFFFFF'}}));const currentBlock=await reader.getBlock('latest');setProof({payload,expiresAt:Date.now()+Math.max(0,deadline-currentBlock.timestamp)*1000,createdAt:Date.now()})}catch(err){setError(userError(err,'generate your check-in code'))}finally{setBusy(false)}}
 const remaining=proof?Math.max(0,Math.floor((proof.expiresAt-clock)/1000)):0;
 return <Modal title={'Ticket '+t.id} onClose={onClose}><div className="modal-body ticket-modal"><span className="mini-brand"><Ticket size={21}/>ticketa.</span><h2>{e.name}</h2><p className="muted">{dateTime(e.startsAt)}<br/>{e.venue}</p><span className={'status '+(t.used?'used':'')}>{t.used?'Checked in':'Unused'}</span><p className="ticket-id">Ticket #{t.id} · {e.tiers[t.tierId]?.name}</p>{error&&<Notice>{error}</Notice>}{!t.used&&(qr&&remaining>0?<><img className="qr" src={qr} alt={'Signed check-in QR code for ticket '+t.id}/><span className="qr-expiry">Expires in {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</span><p className="fine-print">Show this code to authorized event staff. Keep it private.</p><a className="text-button download-code" href={qr} download={'ticketa-'+t.id+'.png'}><Download size={14}/>Download code</a></>:<div className="qr-placeholder"><ScanLine size={42}/><p>{proof?'This code has expired. Generate a new code.':'Generate a signed QR code when you arrive at the event.'}</p></div>)}{!t.used&&<button className="primary-button full" onClick={generate} disabled={busy}>{busy?<><LoaderCircle size={17} className="spin"/>Waiting for your signature…</>:<><ScanLine size={17}/>{proof?'Generate new code':'Generate check-in code'}</>}</button>}<div className="ticket-owner"><ShieldCheck size={17}/>Owned by {shortAddress(t.owner)}</div><div className="ticket-dialog-actions"><a className="outline-button" href={CHAIN.explorer+'/token/'+ADDRESS+'/instance/'+t.id} target="_blank" rel="noreferrer">View on explorer<ArrowUpRight size={15}/></a><button className="outline-button" disabled={t.used||busy} onClick={()=>onTransfer(t)}><ArrowLeftRight size={16}/>Transfer</button></div><p className="fine-print">Signing a code has no network fee. Check-in is confirmed on-chain by event staff.</p></div></Modal>
}
