import React,{useState,useEffect,useRef} from 'react';
import {ArrowLeftRight,ArrowUpRight,ArrowDownLeft,ArrowUpRight as Sent,Ticket} from 'lucide-react';
import {isAddress,getAddress,ZeroAddress} from 'ethers';
import {Modal,Empty,Notice,Loading} from '../components/Shared';
import {readTransfers,DEPLOYMENT_BLOCK,sameAddress,shortAddress,explorerTx,userError} from '../lib/chain';
export function TransferDialog({ticket,event,address,busy,onTransfer,onClose}){const [recipient,setRecipient]=useState(''),[error,setError]=useState('');function submit(e){e.preventDefault();setError('');if(!isAddress(recipient)||sameAddress(recipient,ZeroAddress)){setError('Enter a valid recipient wallet address.');return}if(sameAddress(recipient,address)){setError('Use a different wallet address for the recipient.');return}onTransfer(ticket,getAddress(recipient))}return <Modal title="Transfer ticket" onClose={onClose}><div className="modal-body"><div className="stat-icon blue"><ArrowLeftRight size={23}/></div><h2>Transfer ticket</h2><p className="muted">{event.name} · Ticket #{ticket.id}</p><form className="form" onSubmit={submit}>{error&&<Notice>{error}</Notice>}<label>Recipient wallet address<input required value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="0x…" autoComplete="off"/></label><p className="transfer-warning">Check the full address. Once confirmed, the recipient owns this ticket and it leaves your wallet. Transfers cannot be undone.</p><button className="primary-button full" disabled={busy||ticket.used}>{busy?'Waiting for confirmation…':'Transfer ticket'}<ArrowUpRight size={17}/></button><p className="fine-print">Your wallet will ask you to approve an on-chain transfer. A network fee applies.</p></form></div></Modal>}
export default function Transfers({data,address,busy,onTransfer}){
 const [history,setHistory]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[oldest,setOldest]=useState(null);
 const head=useRef(null),working=useRef(false),alive=useRef(true);
 useEffect(()=>()=>{alive.current=false},[]);
 const merge=entries=>setHistory(prev=>[...new Map([...prev,...entries].map(t=>[t.id,t])).values()].sort((a,b)=>b.block-a.block));
 async function load(older=false){if(working.current)return;working.current=true;setLoading(true);setError('');const end=older?(oldest??data.block)-1:data.block;const start=older||head.current===null?Math.max(DEPLOYMENT_BLOCK,end-4999):Math.max(DEPLOYMENT_BLOCK,head.current-20);try{const rows=await readTransfers(address,end,start);if(alive.current){merge(rows);if(older||head.current===null)setOldest(start);if(!older)head.current=end}}catch(e){if(alive.current)setError(userError(e,'load transfer history'))}finally{working.current=false;if(alive.current)setLoading(false)}}
 useEffect(()=>{load()},[data.block]);
 const unused=data.tickets.filter(t=>!t.used);
 return <><section className="panel"><h2>Transfer a ticket</h2><p className="muted">Send an unused ticket to another wallet on BOT Chain Testnet.</p>{unused.length?unused.map(t=><div className="transfer-row" key={t.id}><div className="stat-icon blue"><Ticket size={22}/></div><div><h3>{data.events.find(e=>e.id===t.eventId)?.name}</h3><p>Ticket #{t.id} · {data.events.find(e=>e.id===t.eventId)?.tiers[t.tierId]?.name}</p></div><button className="outline-button" disabled={busy} onClick={()=>onTransfer(t)}>Transfer<ArrowUpRight size={16}/></button></div>):<Empty icon={ArrowLeftRight} title="No unused tickets">Tickets you buy or receive will appear here. Checked-in tickets cannot be transferred.</Empty>}</section><section className="panel"><div className="section-title"><h2>Transfer history</h2><span className="small-count">BOT Chain records</span></div>{error&&<Notice onRetry={()=>load()}>{error}</Notice>}{history.length?<div className="history-list">{history.map(t=>{const outgoing=sameAddress(t.from,address);return <div className="transfer-row" key={t.id}><div className={'stat-icon '+(outgoing?'orange':'green')}>{outgoing?<Sent size={21}/>:<ArrowDownLeft size={21}/>}</div><div><h3>Ticket #{t.tokenId} · {outgoing?'Sent':'Received'}</h3><p>{outgoing?'To':'From'} {shortAddress(outgoing?t.to:t.from)} · Block {t.block.toLocaleString()}</p></div><a className="outline-button" href={explorerTx(t.hash)} target="_blank" rel="noreferrer">View transaction<ArrowUpRight size={14}/></a></div>})}</div>:!loading&&!error&&<Empty icon={ArrowLeftRight} title="No transfers in this block range">Confirmed transfers involving your wallet appear here.</Empty>}{loading&&<Loading text="Loading transfer history…"/>}{oldest!==null&&<div className="history-pagination"><span>Records from block {oldest.toLocaleString()} onward</span>{oldest>DEPLOYMENT_BLOCK&&<button className="outline-button" disabled={loading} onClick={()=>load(true)}>Load earlier transfers</button>}</div>}</section></>
}
