import React,{useEffect,useRef} from 'react';
import {Ticket,ArrowUpRight,X,LoaderCircle,AlertCircle,Wallet,ArrowRight} from 'lucide-react';
import {CHAIN,ADDRESS,explorerAddress} from '../lib/chain';
export function Brand(){return <a className="brand" href="#/"><span className="brand-mark"><Ticket size={25}/></span>ticketa<span className="brand-dot">.</span></a>}
export function Footer(){return <footer><div><span className="footer-brand">ticketa.</span><p>Your ticket. Your wallet. Your proof.</p></div><div className="ecosystem"><strong>Built on BOT Chain</strong><a href="https://botchain.ai" target="_blank" rel="noreferrer">botchain.ai <ArrowUpRight size={13}/></a><a href="https://scan.botchain.ai" target="_blank" rel="noreferrer">scan.botchain.ai <ArrowUpRight size={13}/></a><a href={explorerAddress(ADDRESS)} target="_blank" rel="noreferrer">Testnet contract <ArrowUpRight size={13}/></a></div></footer>}
export function Modal({title,children,onClose,wide=false}){const ref=useRef(null),previous=useRef(null);useEffect(()=>{previous.current=document.activeElement;ref.current?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;previous.current?.focus()}},[]);return <div className="modal-backdrop" onClick={onClose}><section className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close dialog" onClick={onClose}><X size={20}/></button>{children}</section></div>}
export function Empty({icon:Icon=Ticket,title,children,action,label}){return <div className="empty"><div className="empty-icon"><Icon size={28}/></div><h3>{title}</h3><p>{children}</p>{action&&<button className="primary-button" onClick={action}>{label}<ArrowRight size={16}/></button>}</div>}
export function Loading({text='Loading from BOT Chain…'}){return <div className="loading" role="status"><LoaderCircle className="spin" size={22}/>{text}</div>}
export function Notice({children,onRetry}){return <div className="notice" role="alert"><AlertCircle size={19}/><span>{children}</span>{onRetry&&<button className="text-button" onClick={onRetry}>Try again</button>}</div>}
export function WalletDialog({wallet,onClose}){return <Modal title="Connect wallet" onClose={onClose}><div className="modal-body"><div className="stat-icon blue"><Wallet size={23}/></div><h2>Connect your wallet</h2><p className="muted">Use your wallet to access Ticketa on BOT Chain Testnet.</p>{wallet.error&&<Notice>{wallet.error}</Notice>}{wallet.available.length?<div className="wallet-list">{wallet.available.map((w,i)=><button className="wallet-choice" key={w.uuid||i} disabled={wallet.connecting} onClick={()=>wallet.connect(w)}><Wallet size={22}/><span>{w.name}</span>{wallet.connecting?<LoaderCircle size={17} className="spin"/>:<ArrowRight size={17}/>}</button>)}</div>:<><Notice>No wallet was found in this browser. Install an EVM wallet or open Ticketa in your wallet’s browser, then return here.</Notice><a className="outline-button full" href="https://metamask.io/download/" target="_blank" rel="noreferrer">Get MetaMask<ArrowUpRight size={16}/></a><a className="text-button" href="https://wallet.botchain.ai" target="_blank" rel="noreferrer">BOT Chain wallet<ArrowUpRight size={16}/></a></>}<p className="fine-print">You’ll be asked to approve the connection and switch to {CHAIN.name}. Connecting does not spend BOT.</p></div></Modal>}
export const dateTime=seconds=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(seconds*1000));
export const eventState=(e,now)=>now>=e.endsAt?'Ended':now>=e.startsAt?'In progress':'Upcoming';
